name: powerpulse
description: "A new Flutter project."

# Prevent accidental publishing to pub.dev.
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ^3.7.2

dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter
  hive: ^2.2.3
  hive_flutter: ^1.1.0
  collection: any
  network_tools: ^5.0.2
  path_provider: ^2.1.4
  network_info_plus: ^6.1.0
  lan_scanner: ^4.0.0
  sidebarx: ^0.17.1
  web_socket_channel: ^2.3.0
  msgpack_dart: ^1.0.1
  intl: ^0.19.0
  flutter_markdown: ^0.7.4+3
  expressions: ^0.2.5+2
  ml_linalg: ^13.12.6
  crypto: ^3.0.6
  fl_chart: ^1.0.0

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^4.0.0
  hive_generator: ^2.0.1
  build_runner: ^2.4.13

flutter:
  uses-material-design: true

  # Enable generation of localized Strings from arb files.
  generate: true

  assets:
    # Add assets from the images directory to the application.
    - assets/images/
